[package]
name = "mcjs_test262"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mcjs_vm = { path = "../mcjs_vm" }
anyhow = "1.0"
serde = "1.0"
serde_json = "1.0.108"
serde_yaml = "0.9.29"


