[package]
name = "mcjs_tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
handlebars = { version = "4.4.0", features = ["dir_source"] }
listenfd = "1.0.1"
mcjs_vm = { path = "../mcjs_vm", features = ["debugger"] }
serde_json = "1.0.107"

