// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Group struct {
	PathHash  string
	GroupHash string
}

type Run struct {
	PathHash         string
	IsStrict         bool
	ErrorCategory    sql.NullString
	Version          string
	ErrorMessageHash sql.NullString
}

type String struct {
	String string
	Hash   string
}

type Testcase struct {
	PathHash      string
	ExpectedError sql.NullString
}
