// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Group struct {
	PathHash  sql.NullString
	GroupHash sql.NullString
}

type Run struct {
	PathHash         sql.NullString
	IsStrict         sql.NullBool
	ErrorCategory    sql.NullString
	Version          sql.NullString
	ErrorMessageHash sql.NullString
}

type String struct {
	String sql.NullString
	Hash   sql.NullString
}

type Testcase struct {
	PathHash      sql.NullString
	ExpectedError sql.NullString
}
